
---
#error: true
#warn: true
#info: true
#debug: true
#trace: true

server:
  port: 8091

logging:
  pattern:
    console: " %replace(%m%wEx){'\\n','\r'}%n"
#    console: "%d [%thread] %5p %logger: %replace(%m%wEx){'\\n','\r'}%nopex%n"
  level:
#   ru.vip.demo: TRACE#
   ru.vip.demo: DEBUG#
#   ru.vip.demo: WARN#

#    org.zalando.logbook.Logbook: TRACE#
#    org.zalando.logbook.Logbook: TRACE#
#    ru.x5.omni.messaging.aop.MessageLogging: TRACE
#   org.springframework.kafka.test.utils: DEBUG
#    org.hibernate.SQL: DEBUG
#==========================================
#     DB H2
#==========================================
spring:
  datasource:
    username: sa
    password:
    driverClassName: org.h2.Driver
    # temporary data storage
    url: jdbc:h2:mem:customers;DB_CLOSE_ON_EXIT=FALSE
    # url: jdbc:h2:file:C:/data/customers;DB_CLOSE_DELAY=-1
    schema: classpath*:database/initDB.sql
    initialization-mode: ALWAYS
  h2:
    console:
      enabled: true

# ===============================
# JPA / HIBERNATE
# ===============================
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

