
---
server:
  port: 8091

# Передача отдельных переменных (names.test & names.number) в Класс приложения
names:
  test: "TestProviderApplication"
  number: 23

# Передача блока переменных 4шт (provider.params) в Класс приложения
provider:
  params:
    TARGET_BEAN: "?"
    COUNT_METHOD: 1
    LIST_BEAN: 10, 20
    ORIGINAL_STRING: false

#==========================================
#     LOGGING -настройка логирования
#==========================================
logging:
  level:
    # root: off #
    ru.vip.demo: debug                                                      # Уровень DEBUG
  pattern:                                                                  # Формат вывода
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{44} - %msg%n"         # В консоль
    file: "%d{yyyy-MM-DD HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n" # В файл
  file:
    name: application.log                                                   # Файл вывода логов

  #==========================================
  #     DB H2 -настройка Базы Данных
  #==========================================
spring:
  #main:
    #log-startup-info: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:customers;DB_CLOSE_ON_EXIT=FALSE
    # url: jdbc:h2:file:C:/data/demo;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true


    # temporary data storage
    # schema: classpath*:database/initDB.sql
    # initialization-mode: ALWAYS
# ===============================
# JPA / HIBERNATE
# ===============================
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

    # database-platform: org.hibernate.dialect.H2Dialect
