
---
#error: true
#warn: true
#info: true
#debug: true
#trace: true
names:
  test: "TestProviderApplication"
  number: 23

provider:
  params:
    TARGET_BEAN: "Jpa"
    COUNT_METHOD: 2
    LIST_BEAN: 39, 48, 59
    ORIGINAL_STRING: false

server:
  port: 8091

#==========================================
#     LOGGING
#==========================================

logging:
  level:
    org.springframework.*: ERROR#
    ru.vip.demo: DEBUG#
  pattern:
    console: " %msg%n"
    #  console: " %replace(%m%wEx){'\\n','\r'}%n"
    #    console: "%d [%thread] %5p %logger: %replace(%m%wEx){'\\n','\r'}%nopex%n"
    file: "%d{yyyy-MM-DD HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: application.log

#   ru.vip.demo: TRACE#
#   ru.vip.demo: INFO#
#    ru.vip.demo: WARN#
#    ru.vip.demo: ERROR#
#    ru.vip.demo: FATAL#
#    ru.vip.demo: OFF#



#==========================================
#     DB H2
#==========================================
spring:
  main:
    banner-mode: off

  datasource:
    username: sa
    password:
    driverClassName: org.h2.Driver
    # temporary data storage
    url: jdbc:h2:mem:customers;DB_CLOSE_ON_EXIT=FALSE
    # url: jdbc:h2:file:C:/data/customers;DB_CLOSE_DELAY=-1
    schema: classpath*:database/initDB.sql
    initialization-mode: ALWAYS
  h2:
    console:
      enabled: true

# ===============================
# JPA / HIBERNATE
# ===============================
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

